services:
  backend:
    build: ./backend
    volumes:
      - db_data:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: ./backend
      dockerfile: celery.Dockerfile
    volumes:
      - db_data:/app
    depends_on:
      - backend
      - redis

  redis:
    image: redis:alpine

  frontend:
    build: ./ahoum-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
